exp_name: 
total_timesteps: 1000000

# TD3 parameters
learning_rate: 3e-4
tau: 0.005
batch_size: 256
policy_noise: 0.2
exploration_noise: 0.1
learning_starts: 25e3
policy_frequency: 2
noise_clip: 0.5

# OPPONENT / SELF-PLAY parameters
weak_opponent: false
is_self_play: false
self_play_initial_opponents:
  - - weak
    - 1200
  - - strong
    - 1500
self_play_reuse_opponent_exp: false

# COLORED NOISE parameters (to disable, set "noise_type" to "normal")
noise_type: normal
noise_beta: 1.0
noise_sigma: 0.2

# RND parameters
rnd_int_coef: 0
rnd_ext_coef: 1
rnd_update_proportion: 0.25
rnd_feature_size: 512
rnd_num_iterations_obs_norm_init: 50
rnd_max_intrinsic_reward: 1.0
rnd_recompute_int_reward_on_replay: false
rnd_learning_rate: 1e-5
