# NOTE: this code was generated by ChatGPT and is only used to extract the scalar data from the tensorboard logs. 

import tensorflow as tf
import matplotlib.pyplot as plt

import os
import pandas as pd
from tensorboard.backend.event_processing import event_accumulator
from tqdm import tqdm

def save_scalar_data(path, output_dir):
    ea = event_accumulator.EventAccumulator(path)
    ea.Reload()

    # Get all scalar tags
    scalar_tags = ea.Tags()['scalars']

    for tag in scalar_tags:
        events = ea.Scalars(tag)
        
        df = pd.DataFrame({
            "step": [e.step for e in events],
            "value": [e.value for e in events],
            "wall_time": [e.wall_time for e in events],
        })
        
        # sanitize tag name for filename
        filename = tag.replace("/", "-") + ".csv"
        
        df.to_csv(os.path.join(output_dir, filename), index=False)


log_dir = "./runs"
output_dir = "./data"
for run in tqdm(os.listdir(log_dir)):
    for file in os.listdir(os.path.join(log_dir, run)):
        if file.startswith("events.out.tfevents"):
            out_dir = f"./data/{run}"
            os.makedirs(out_dir, exist_ok=True)
            in_path = os.path.join(log_dir, run, file)
            save_scalar_data(in_path, out_dir)
print("Done.")
